# Site settings
title: Hexo Wiki
subtitle: WIKI PAGES
description: This is wiki themes demo
author: your-name
language: zh-CN

# Themes settings
rss: atom.xml
favicon: favicon.ico
fold: false  # Whether to fold all the notebooks initially
scratch_name: Scratch  # Notebook name of posts without categories variables
google_analytics:
search:
  path: search.xml
  field: all