# Site settings
title: Wiki Pages
subtitle: Mine Wiki
description:
author: itaken
language: zh-CN

# Themes settings
rss: atom.xml
favicon: favicon.ico
fold: false  # Whether to fold all the notebooks initially
scratch_name: Scratch  # Notebook name of posts without categories variables
google_analytics:
search:
  path: search.xml
  field: all
